"""updated the date time in inspection

Revision ID: 0f7bd3cb99cb
Revises: 8c2a7b4f1d9e
Create Date: 2026-06-16 18:14:03.432144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7bd3cb99cb'
down_revision: Union[str, Sequence[str], None] = '8c2a7b4f1d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('defects', 'ai_recommendation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('defects', 'ai_recommendation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    # ### end Alembic commands ###
