"""added defect field for recommendation

Revision ID: 1def940f3fff
Revises: de6d36c890d8
Create Date: 2026-06-16 15:04:51.403570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1def940f3fff'
down_revision: Union[str, Sequence[str], None] = 'de6d36c890d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defects', sa.Column('ai_recommendation', sa.Text(), nullable=True,server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defects', 'ai_recommendation')
    # ### end Alembic commands ###
