"""add_new_fields_to_models

Revision ID: de6d36c890d8
Revises: e842836dcf36
Create Date: 2026-06-16 10:35:23.537794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de6d36c890d8'
down_revision: Union[str, Sequence[str], None] = 'e842836dcf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('asset_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'asset_name')
    # ### end Alembic commands ###
