"""initial schema

Revision ID: e842836dcf36
Revises: 
Create Date: 2026-06-04 16:07:02.749136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e842836dcf36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('TRANSMISSION_TOWER', 'OHE_RAIL', 'DISTRIBUTION_POLE', name='assettype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('installed_year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('risk_30_days', sa.Float(), nullable=False),
    sa.Column('risk_60_days', sa.Float(), nullable=False),
    sa.Column('risk_90_days', sa.Float(), nullable=False),
    sa.Column('degradation_rate', sa.Float(), nullable=False),
    sa.Column('at_risk_component', sa.String(), nullable=False),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('inspection_history_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('pilot_id', sa.String(), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=False),
    sa.Column('capture_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('validation_status', sa.Enum('PENDING', 'PASSED', 'FAILED', name='validationstatus'), nullable=False),
    sa.Column('validation_notes', sa.JSON(), nullable=False),
    sa.Column('analysis_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysisstatus'), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection', sa.UUID(), nullable=False),
    sa.Column('defect_type', sa.Enum('CORROSION', 'VEGETATION_ENCROACHMENT', 'MISSING_COMPONENT', 'SAG', 'CRACK', 'HOTSPOT', 'OTHER', name='defecttype'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='severity'), nullable=False),
    sa.Column('location_description', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=False),
    sa.Column('raw_ai_response', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['inspection'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('defect_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', name='ticketpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='ticketstatus'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('assigned_team', sa.String(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('before_photo_path', sa.String(), nullable=True),
    sa.Column('after_photo_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('defects')
    op.drop_table('inspections')
    op.drop_table('forecasts')
    op.drop_table('assets')
    # ### end Alembic commands ###
